fixing install script error handling (file redirection)

diff --git a/install b/install
--- a/install
+++ b/install
@@ -6,14 +6,14 @@ zsh_config_setup() {
 	local -r ZSHCONFIG="${ZDOTDIR:-$HOME}/.zsh-config"
 
 	# dependency checks
-	[[ -f "${ZSHCONFIG}/lib/fzf/completion.zsh" ]]   || { echo "lib/fzf/competion.zsh not found!" >2; exit 1; }
-	[[ -f "${ZSHCONFIG}/lib/fzf/key-bindings.zsh" ]] || { echo "lib/fzf/keybindings.zsh not found!" >2; exit 1; }
-	command -v "antibody" >/dev/null 2>&1            || { echo "Antibody not found!" >2; exit 1; }
+	[[ -f "${ZSHCONFIG}/lib/fzf/completion.zsh" ]]   || { echo "lib/fzf/competion.zsh not found!" >&2; exit 1; }
+	[[ -f "${ZSHCONFIG}/lib/fzf/key-bindings.zsh" ]] || { echo "lib/fzf/keybindings.zsh not found!" >&2; exit 1; }
+	command -v "antibody" >/dev/null 2>&1            || { echo "Antibody not found!" >&2; exit 1; }
 
 	echo 'Installing antibody plugins ... '
 	antibody bundle < "${ZSHCONFIG}/antibody/zsh-antibody-plugins-list" \
 			> "${ZSHCONFIG}/antibody/zsh-managed-plugins.zsh" || \
-		       	{ echo "Antibody setup failed!" >2; exit 1; }
+		       	{ echo "Antibody setup failed!" >&2; exit 1; }
 	echo '> Done!'
 
 	local -r zfiles="${ZSHCONFIG}/zfiles"
